# This is the limmat.toml for _hacking on this repository_, it is not intended
# for kernel development.
[[tests]]
name = "flake-check"
command = "nix flake check"

[[tests]]
name = "test-golden"
command = "nix run .#test-golden"